#!/bin/bash
./feature output/00_0.calcA
./feature output/01_0.calcA output/01_1.calcA output/01_2.calcA output/01_3.calcA output/01_4.calcA
./feature output/02-1_0.calcA output/02-1_1.calcA output/02-1_2.calcA output/02-1_3.calcA output/02-1_4.calcA
./feature output/02-2_0.calcA output/02-2_1.calcA output/02-2_2.calcA output/02-2_3.calcA output/02-2_4.calcA
./feature output/03_0.calcA output/03_1.calcA output/03_2.calcA output/03_3.calcA output/03_4.calcA
./feature output/04_0.calcA output/04_1.calcA output/04_2.calcA output/04_3.calcA output/04_4.calcA
./feature output/05_0.calcA output/05_1.calcA output/05_2.calcA output/05_3.calcA output/05_4.calcA
./feature output/06_0.calcA output/06_1.calcA output/06_2.calcA output/06_3.calcA output/06_4.calcA
./feature output/07_0.calcA output/07_1.calcA output/07_2.calcA output/07_3.calcA output/07_4.calcA
./feature output/08_0.calcA output/08_1.calcA output/08_2.calcA output/08_3.calcA output/08_4.calcA
./feature output/09_0.calcA output/09_1.calcA output/09_2.calcA output/09_3.calcA output/09_4.calcA
./feature output/10_0.calcA output/10_1.calcA output/10_2.calcA output/10_3.calcA output/10_4.calcA
./feature output/11_0.calcA output/11_1.calcA output/11_2.calcA output/11_3.calcA output/11_4.calcA
./feature output/12_0.calcA output/12_1.calcA output/12_2.calcA output/12_3.calcA output/12_4.calcA
./feature output/13-1_0.calcA output/13-1_1.calcA output/13-1_2.calcA output/13-1_3.calcA output/13-1_4.calcA
./feature output/13-2_0.calcA output/13-2_1.calcA output/13-2_2.calcA output/13-2_3.calcA output/13-2_4.calcA
./feature output/14_0.calcA output/14_1.calcA output/14_2.calcA output/14_3.calcA output/14_4.calcA
./feature output/15_0.calcA output/15_1.calcA output/15_2.calcA output/15_3.calcA output/15_4.calcA
./feature output/16_0.calcA output/16_1.calcA output/16_2.calcA output/16_3.calcA output/16_4.calcA
./feature output/17_0.calcA output/17_1.calcA output/17_2.calcA output/17_3.calcA output/17_4.calcA
./feature output/18_0.calcA output/18_1.calcA output/18_2.calcA output/18_3.calcA output/18_4.calcA
./feature output/19_0.calcA output/19_1.calcA output/19_2.calcA output/19_3.calcA output/19_4.calcA
./feature output/20_0.calcA output/20_1.calcA output/20_2.calcA output/20_3.calcA output/20_4.calcA
./feature output/21_0.calcA output/21_1.calcA output/21_2.calcA output/21_3.calcA output/21_4.calcA
./feature output/22-00_0.calcA
./feature output/22-0_0.calcA
./feature output/22-01_0.calcA
./feature output/22-02_0.calcA
./feature output/22-03_0.calcA
./feature output/22-04_0.calcA
./feature output/22-05_0.calcA
./feature output/22-06_0.calcA
./feature output/22-07_0.calcA
./feature output/22-08_0.calcA
./feature output/22-09_0.calcA
./feature output/22-10_0.calcA
./feature output/22-11_0.calcA
./feature output/22-12_0.calcA
./feature output/22-13_0.calcA
./feature output/22-14_0.calcA
./feature output/22-15_0.calcA
./feature output/23-1_0.calcA
./feature output/23-2_0.calcA
./feature output/23-3_0.calcA
./feature output/23-4_0.calcA
./feature output/23-5_0.calcA
./feature output/23-6_0.calcA
./feature output/23-7_0.calcA
./feature output/23-8_0.calcA
./feature output/23-9_0.calcA
./feature output/24_0.calcA output/24_1.calcA output/24_2.calcA output/24_3.calcA output/24_4.calcA
./feature output/25_0.calcA output/25_1.calcA output/25_2.calcA output/25_3.calcA output/25_4.calcA
./feature output/26_0.calcA output/26_1.calcA output/26_2.calcA output/26_3.calcA output/26_4.calcA
./feature output/27_0.calcA output/27_1.calcA output/27_2.calcA output/27_3.calcA output/27_4.calcA
./feature output/28_0.calcA output/28_1.calcA output/28_2.calcA output/28_3.calcA output/28_4.calcA
./feature output/29_0.calcA output/29_1.calcA output/29_2.calcA output/29_3.calcA output/29_4.calcA
./feature output/30_0.calcA output/30_1.calcA output/30_2.calcA output/30_3.calcA output/30_4.calcA
./feature output/31_0.calcA output/31_1.calcA output/31_2.calcA output/31_3.calcA output/31_4.calcA
./feature output/32_0.calcA output/32_1.calcA output/32_2.calcA output/32_3.calcA output/32_4.calcA
./feature output/33-1_0.calcA output/33-1_1.calcA output/33-1_2.calcA output/33-1_3.calcA output/33-1_4.calcA
./feature output/33-2_0.calcA output/33-2_1.calcA output/33-2_2.calcA output/33-2_3.calcA output/33-2_4.calcA
./feature output/33-3_0.calcA output/33-3_1.calcA output/33-3_2.calcA output/33-3_3.calcA output/33-3_4.calcA
./feature output/34_0.calcA output/34_1.calcA output/34_2.calcA output/34_3.calcA output/34_4.calcA
./feature output/35_0.calcA output/35_1.calcA output/35_2.calcA output/35_3.calcA output/35_4.calcA
./feature output/36_0.calcA output/36_1.calcA output/36_2.calcA output/36_3.calcA output/36_4.calcA
./feature output/37_0.calcA output/37_1.calcA output/37_2.calcA output/37_3.calcA output/37_4.calcA
./feature output/38-1_0.calcA output/38-1_1.calcA output/38-1_2.calcA output/38-1_3.calcA output/38-1_4.calcA
./feature output/38-2_0.calcA output/38-2_1.calcA output/38-2_2.calcA output/38-2_3.calcA output/38-2_4.calcA
./feature output/38-3_0.calcA output/38-3_1.calcA output/38-3_2.calcA output/38-3_3.calcA output/38-3_4.calcA
./feature output/39-1_0.calcA
./feature output/39-2_0.calcA
./feature output/39-3_0.calcA
